<?php

namespace AppBundle\Repository;

/**
 * CookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CookRepository extends \Doctrine\ORM\EntityRepository
{
}
